// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:braid_ui/freetype')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Pointer<ffi.Char> Function(FTError)>(symbol: 'FT_Error_String')
external ffi.Pointer<ffi.Char> ftErrorString(int error_code);

@ffi.Native<FTError Function(ffi.Pointer<FTLibrary>)>(
  symbol: 'FT_Init_FreeType',
)
external int ftInitFreetype(ffi.Pointer<FTLibrary> alibrary);

@ffi.Native<FTError Function(FTLibrary)>(symbol: 'FT_Done_FreeType')
external int ftDoneFreetype(FTLibrary library);

@ffi.Native<
  FTError Function(
    FTLibrary,
    ffi.Pointer<ffi.Char>,
    FTLong,
    ffi.Pointer<FTFace>,
  )
>(symbol: 'FT_New_Face')
external int ftNewFace(
  FTLibrary library,
  ffi.Pointer<ffi.Char> filepathname,
  int face_index,
  ffi.Pointer<FTFace> aface,
);

@ffi.Native<
  FTError Function(
    FTLibrary,
    ffi.Pointer<FTByte>,
    FTLong,
    FTLong,
    ffi.Pointer<FTFace>,
  )
>(symbol: 'FT_New_Memory_Face')
external int ftNewMemoryFace(
  FTLibrary library,
  ffi.Pointer<FTByte> file_base,
  int file_size,
  int face_index,
  ffi.Pointer<FTFace> aface,
);

@ffi.Native<
  FTError Function(
    FTLibrary,
    ffi.Pointer<FTOpenArgs>,
    FTLong,
    ffi.Pointer<FTFace>,
  )
>(symbol: 'FT_Open_Face')
external int ftOpenFace(
  FTLibrary library,
  ffi.Pointer<FTOpenArgs> args,
  int face_index,
  ffi.Pointer<FTFace> aface,
);

@ffi.Native<FTError Function(FTFace, ffi.Pointer<ffi.Char>)>(
  symbol: 'FT_Attach_File',
)
external int ftAttachFile(FTFace face, ffi.Pointer<ffi.Char> filepathname);

@ffi.Native<FTError Function(FTFace, ffi.Pointer<FTOpenArgs>)>(
  symbol: 'FT_Attach_Stream',
)
external int ftAttachStream(FTFace face, ffi.Pointer<FTOpenArgs> parameters);

@ffi.Native<FTError Function(FTFace)>(symbol: 'FT_Reference_Face')
external int ftReferenceFace(FTFace face);

@ffi.Native<FTError Function(FTFace)>(symbol: 'FT_Done_Face')
external int ftDoneFace(FTFace face);

@ffi.Native<FTError Function(FTFace, FTInt)>(symbol: 'FT_Select_Size')
external int ftSelectSize(FTFace face, int strike_index);

@ffi.Native<FTError Function(FTFace, FTSizeRequest)>(symbol: 'FT_Request_Size')
external int ftRequestSize(FTFace face, FTSizeRequest req);

@ffi.Native<FTError Function(FTFace, FTF26dot6, FTF26dot6, FTUint, FTUint)>(
  symbol: 'FT_Set_Char_Size',
)
external int ftSetCharSize(
  FTFace face,
  int char_width,
  int char_height,
  int horz_resolution,
  int vert_resolution,
);

@ffi.Native<FTError Function(FTFace, FTUint, FTUint)>(
  symbol: 'FT_Set_Pixel_Sizes',
)
external int ftSetPixelSizes(FTFace face, int pixel_width, int pixel_height);

@ffi.Native<FTError Function(FTFace, FTUint, FTInt32)>(symbol: 'FT_Load_Glyph')
external int ftLoadGlyph(FTFace face, int glyph_index, int load_flags);

@ffi.Native<FTError Function(FTFace, FTUlong, FTInt32)>(symbol: 'FT_Load_Char')
external int ftLoadChar(FTFace face, int char_code, int load_flags);

@ffi.Native<
  ffi.Void Function(FTFace, ffi.Pointer<FTMatrix>, ffi.Pointer<FTVector>)
>(symbol: 'FT_Set_Transform')
external void ftSetTransform(
  FTFace face,
  ffi.Pointer<FTMatrix> matrix,
  ffi.Pointer<FTVector> delta,
);

@ffi.Native<
  ffi.Void Function(FTFace, ffi.Pointer<FTMatrix>, ffi.Pointer<FTVector>)
>(symbol: 'FT_Get_Transform')
external void ftGetTransform(
  FTFace face,
  ffi.Pointer<FTMatrix> matrix,
  ffi.Pointer<FTVector> delta,
);

@ffi.Native<FTError Function(FTGlyphslot, ffi.UnsignedInt)>(
  symbol: 'FT_Render_Glyph',
)
external int _ftRenderGlyph(FTGlyphslot slot, int render_mode);

DartFTError ftRenderGlyph(FTGlyphslot slot, FTRenderMode_ render_mode) =>
    _ftRenderGlyph(slot, render_mode.value);

@ffi.Native<
  FTError Function(FTFace, FTUint, FTUint, FTUint, ffi.Pointer<FTVector>)
>(symbol: 'FT_Get_Kerning')
external int ftGetKerning(
  FTFace face,
  int left_glyph,
  int right_glyph,
  int kern_mode,
  ffi.Pointer<FTVector> akerning,
);

@ffi.Native<FTError Function(FTFace, FTFixed, FTInt, ffi.Pointer<FTFixed>)>(
  symbol: 'FT_Get_Track_Kerning',
)
external int ftGetTrackKerning(
  FTFace face,
  int point_size,
  int degree,
  ffi.Pointer<FTFixed> akerning,
);

@ffi.Native<FTError Function(FTFace, ffi.UnsignedInt)>(
  symbol: 'FT_Select_Charmap',
)
external int _ftSelectCharmap(FTFace face, int encoding);

DartFTError ftSelectCharmap(FTFace face, FTEncoding_ encoding) =>
    _ftSelectCharmap(face, encoding.value);

@ffi.Native<FTError Function(FTFace, FTCharmap)>(symbol: 'FT_Set_Charmap')
external int ftSetCharmap(FTFace face, FTCharmap charmap);

@ffi.Native<FTInt Function(FTCharmap)>(symbol: 'FT_Get_Charmap_Index')
external int ftGetCharmapIndex(FTCharmap charmap);

@ffi.Native<FTUint Function(FTFace, FTUlong)>(symbol: 'FT_Get_Char_Index')
external int ftGetCharIndex(FTFace face, int charcode);

@ffi.Native<FTUlong Function(FTFace, ffi.Pointer<FTUint>)>(
  symbol: 'FT_Get_First_Char',
)
external int ftGetFirstChar(FTFace face, ffi.Pointer<FTUint> agindex);

@ffi.Native<FTUlong Function(FTFace, FTUlong, ffi.Pointer<FTUint>)>(
  symbol: 'FT_Get_Next_Char',
)
external int ftGetNextChar(
  FTFace face,
  int char_code,
  ffi.Pointer<FTUint> agindex,
);

@ffi.Native<FTError Function(FTFace, FTUint, ffi.Pointer<FTParameter>)>(
  symbol: 'FT_Face_Properties',
)
external int ftFaceProperties(
  FTFace face,
  int num_properties,
  ffi.Pointer<FTParameter> properties,
);

@ffi.Native<FTUint Function(FTFace, ffi.Pointer<FTString>)>(
  symbol: 'FT_Get_Name_Index',
)
external int ftGetNameIndex(FTFace face, ffi.Pointer<FTString> glyph_name);

@ffi.Native<FTError Function(FTFace, FTUint, FTPointer, FTUint)>(
  symbol: 'FT_Get_Glyph_Name',
)
external int ftGetGlyphName(
  FTFace face,
  int glyph_index,
  FTPointer buffer,
  int buffer_max,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(FTFace)>(
  symbol: 'FT_Get_Postscript_Name',
)
external ffi.Pointer<ffi.Char> ftGetPostscriptName(FTFace face);

@ffi.Native<
  FTError Function(
    FTGlyphslot,
    FTUint,
    ffi.Pointer<FTInt>,
    ffi.Pointer<FTUint>,
    ffi.Pointer<FTInt>,
    ffi.Pointer<FTInt>,
    ffi.Pointer<FTMatrix>,
  )
>(symbol: 'FT_Get_SubGlyph_Info')
external int ftGetSubglyphInfo(
  FTGlyphslot glyph,
  int sub_index,
  ffi.Pointer<FTInt> p_index,
  ffi.Pointer<FTUint> p_flags,
  ffi.Pointer<FTInt> p_arg1,
  ffi.Pointer<FTInt> p_arg2,
  ffi.Pointer<FTMatrix> p_transform,
);

@ffi.Native<FTUshort Function(FTFace)>(symbol: 'FT_Get_FSType_Flags')
external int ftGetFstypeFlags(FTFace face);

@ffi.Native<FTUint Function(FTFace, FTUlong, FTUlong)>(
  symbol: 'FT_Face_GetCharVariantIndex',
)
external int ftFaceGetcharvariantindex(
  FTFace face,
  int charcode,
  int variantSelector,
);

@ffi.Native<FTInt Function(FTFace, FTUlong, FTUlong)>(
  symbol: 'FT_Face_GetCharVariantIsDefault',
)
external int ftFaceGetcharvariantisdefault(
  FTFace face,
  int charcode,
  int variantSelector,
);

@ffi.Native<ffi.Pointer<FTUint32> Function(FTFace)>(
  symbol: 'FT_Face_GetVariantSelectors',
)
external ffi.Pointer<FTUint32> ftFaceGetvariantselectors(FTFace face);

@ffi.Native<ffi.Pointer<FTUint32> Function(FTFace, FTUlong)>(
  symbol: 'FT_Face_GetVariantsOfChar',
)
external ffi.Pointer<FTUint32> ftFaceGetvariantsofchar(
  FTFace face,
  int charcode,
);

@ffi.Native<ffi.Pointer<FTUint32> Function(FTFace, FTUlong)>(
  symbol: 'FT_Face_GetCharsOfVariant',
)
external ffi.Pointer<FTUint32> ftFaceGetcharsofvariant(
  FTFace face,
  int variantSelector,
);

@ffi.Native<FTLong Function(FTLong, FTLong, FTLong)>(symbol: 'FT_MulDiv')
external int ftMuldiv(int a, int b, int c);

@ffi.Native<FTLong Function(FTLong, FTLong)>(symbol: 'FT_MulFix')
external int ftMulfix(int a, int b);

@ffi.Native<FTLong Function(FTLong, FTLong)>(symbol: 'FT_DivFix')
external int ftDivfix(int a, int b);

@ffi.Native<FTFixed Function(FTFixed)>(symbol: 'FT_RoundFix')
external int ftRoundfix(int a);

@ffi.Native<FTFixed Function(FTFixed)>(symbol: 'FT_CeilFix')
external int ftCeilfix(int a);

@ffi.Native<FTFixed Function(FTFixed)>(symbol: 'FT_FloorFix')
external int ftFloorfix(int a);

@ffi.Native<ffi.Void Function(ffi.Pointer<FTVector>, ffi.Pointer<FTMatrix>)>(
  symbol: 'FT_Vector_Transform',
)
external void ftVectorTransform(
  ffi.Pointer<FTVector> vector,
  ffi.Pointer<FTMatrix> matrix,
);

@ffi.Native<
  ffi.Void Function(
    FTLibrary,
    ffi.Pointer<FTInt>,
    ffi.Pointer<FTInt>,
    ffi.Pointer<FTInt>,
  )
>(symbol: 'FT_Library_Version')
external void ftLibraryVersion(
  FTLibrary library,
  ffi.Pointer<FTInt> amajor,
  ffi.Pointer<FTInt> aminor,
  ffi.Pointer<FTInt> apatch,
);

@ffi.Native<FTBool Function(FTFace)>(symbol: 'FT_Face_CheckTrueTypePatents')
external int ftFaceChecktruetypepatents(FTFace face);

@ffi.Native<FTBool Function(FTFace, FTBool)>(
  symbol: 'FT_Face_SetUnpatentedHinting',
)
external int ftFaceSetunpatentedhinting(FTFace face, int value);

typedef FTInt16 = ffi.Short;
typedef DartFTInt16 = int;
typedef FTUint16 = ffi.UnsignedShort;
typedef DartFTUint16 = int;
typedef FTInt32 = ffi.Int;
typedef DartFTInt32 = int;
typedef FTUint32 = ffi.UnsignedInt;
typedef DartFTUint32 = int;
typedef FTFast = ffi.Int;
typedef DartFTFast = int;
typedef FTUfast = ffi.UnsignedInt;
typedef DartFTUfast = int;
typedef FTInt64 = ffi.Long;
typedef DartFTInt64 = int;
typedef FTUint64 = ffi.UnsignedLong;
typedef DartFTUint64 = int;
typedef FTMemory = ffi.Pointer<FTMemoryrec_>;
typedef FTAllocFunc =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Pointer<ffi.Void> Function(FTMemory memory, ffi.Long size)
      >
    >;
typedef FTFreeFunc =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(FTMemory memory, ffi.Pointer<ffi.Void> block)
      >
    >;
typedef FTReallocFunc =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Pointer<ffi.Void> Function(
          FTMemory memory,
          ffi.Long cur_size,
          ffi.Long new_size,
          ffi.Pointer<ffi.Void> block,
        )
      >
    >;

final class FTMemoryrec_ extends ffi.Struct {
  external ffi.Pointer<ffi.Void> user;

  external FTAllocFunc alloc;

  external FTFreeFunc free;

  external FTReallocFunc realloc;
}

final class FT_StreamDesc_ extends ffi.Union {
  @ffi.Long()
  external int value;

  external ffi.Pointer<ffi.Void> pointer;
}

typedef FTStreamdesc = FT_StreamDesc_;
typedef FTStream = ffi.Pointer<FTStreamrec_>;
typedef FTStreamIofunc =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.UnsignedLong Function(
          FTStream stream,
          ffi.UnsignedLong offset,
          ffi.Pointer<ffi.UnsignedChar> buffer,
          ffi.UnsignedLong count,
        )
      >
    >;
typedef FTStreamClosefunc =
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(FTStream stream)>>;

final class FTStreamrec_ extends ffi.Struct {
  external ffi.Pointer<ffi.UnsignedChar> base;

  @ffi.UnsignedLong()
  external int size;

  @ffi.UnsignedLong()
  external int pos;

  external FTStreamdesc descriptor;

  external FTStreamdesc pathname;

  external FTStreamIofunc read;

  external FTStreamClosefunc close;

  external FTMemory memory;

  external ffi.Pointer<ffi.UnsignedChar> cursor;

  external ffi.Pointer<ffi.UnsignedChar> limit;
}

typedef FTStreamrec = FTStreamrec_;
typedef FTPos = ffi.Long;
typedef DartFTPos = int;

final class FTVector_ extends ffi.Struct {
  @FTPos()
  external int x;

  @FTPos()
  external int y;
}

typedef FTVector = FTVector_;

final class FTBbox_ extends ffi.Struct {
  @FTPos()
  external int xmin;

  @FTPos()
  external int ymin;

  @FTPos()
  external int xmax;

  @FTPos()
  external int ymax;
}

typedef FTBbox = FTBbox_;

enum FTPixelMode_ {
  pixelModeNone(0),
  pixelModeMono(1),
  pixelModeGray(2),
  pixelModeGray2(3),
  pixelModeGray4(4),
  pixelModeLcd(5),
  pixelModeLcdV(6),
  pixelModeBgra(7),
  pixelModeMax(8);

  final int value;
  const FTPixelMode_(this.value);

  static FTPixelMode_ fromValue(int value) => switch (value) {
    0 => pixelModeNone,
    1 => pixelModeMono,
    2 => pixelModeGray,
    3 => pixelModeGray2,
    4 => pixelModeGray4,
    5 => pixelModeLcd,
    6 => pixelModeLcdV,
    7 => pixelModeBgra,
    8 => pixelModeMax,
    _ => throw ArgumentError('Unknown value for FTPixelMode_: $value'),
  };
}

final class FTBitmap_ extends ffi.Struct {
  @ffi.UnsignedInt()
  external int rows;

  @ffi.UnsignedInt()
  external int width;

  @ffi.Int()
  external int pitch;

  external ffi.Pointer<ffi.UnsignedChar> buffer;

  @ffi.UnsignedShort()
  external int numGrays;

  @ffi.UnsignedChar()
  external int pixelMode;

  @ffi.UnsignedChar()
  external int paletteMode;

  external ffi.Pointer<ffi.Void> palette;
}

typedef FTBitmap = FTBitmap_;

final class FTOutline_ extends ffi.Struct {
  @ffi.UnsignedShort()
  external int nContours;

  @ffi.UnsignedShort()
  external int nPoints;

  external ffi.Pointer<FTVector> points;

  external ffi.Pointer<ffi.UnsignedChar> tags;

  external ffi.Pointer<ffi.UnsignedShort> contours;

  @ffi.Int()
  external int flags;
}

typedef FTOutline = FTOutline_;
typedef FTOutlineMovetofunc =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int Function(ffi.Pointer<FTVector> to, ffi.Pointer<ffi.Void> user)
      >
    >;
typedef FTOutlineLinetofunc =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int Function(ffi.Pointer<FTVector> to, ffi.Pointer<ffi.Void> user)
      >
    >;
typedef FTOutlineConictofunc =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int Function(
          ffi.Pointer<FTVector> control,
          ffi.Pointer<FTVector> to,
          ffi.Pointer<ffi.Void> user,
        )
      >
    >;
typedef FTOutlineCubictofunc =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int Function(
          ffi.Pointer<FTVector> control1,
          ffi.Pointer<FTVector> control2,
          ffi.Pointer<FTVector> to,
          ffi.Pointer<ffi.Void> user,
        )
      >
    >;

final class FTOutlineFuncs_ extends ffi.Struct {
  external FTOutlineMovetofunc moveTo;

  external FTOutlineLinetofunc lineTo;

  external FTOutlineConictofunc conicTo;

  external FTOutlineCubictofunc cubicTo;

  @ffi.Int()
  external int shift;

  @FTPos()
  external int delta;
}

typedef FTOutlineFuncs = FTOutlineFuncs_;

enum FTGlyphFormat_ {
  glyphFormatNone(0),
  glyphFormatComposite(1668246896),
  glyphFormatBitmap(1651078259),
  glyphFormatOutline(1869968492),
  glyphFormatPlotter(1886154612),
  glyphFormatSvg(1398163232);

  final int value;
  const FTGlyphFormat_(this.value);

  static FTGlyphFormat_ fromValue(int value) => switch (value) {
    0 => glyphFormatNone,
    1668246896 => glyphFormatComposite,
    1651078259 => glyphFormatBitmap,
    1869968492 => glyphFormatOutline,
    1886154612 => glyphFormatPlotter,
    1398163232 => glyphFormatSvg,
    _ => throw ArgumentError('Unknown value for FTGlyphFormat_: $value'),
  };
}

final class FTSpan_ extends ffi.Struct {
  @ffi.Short()
  external int x;

  @ffi.UnsignedShort()
  external int len;

  @ffi.UnsignedChar()
  external int coverage;
}

typedef FTSpan = FTSpan_;
typedef FTSpanfunc =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Int y,
          ffi.Int count,
          ffi.Pointer<FTSpan> spans,
          ffi.Pointer<ffi.Void> user,
        )
      >
    >;
typedef FTRasterBittestFunc =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int Function(ffi.Int y, ffi.Int x, ffi.Pointer<ffi.Void> user)
      >
    >;
typedef FTRasterBitsetFunc =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Int y, ffi.Int x, ffi.Pointer<ffi.Void> user)
      >
    >;

final class FTRasterParams_ extends ffi.Struct {
  external ffi.Pointer<FTBitmap> target;

  external ffi.Pointer<ffi.Void> source;

  @ffi.Int()
  external int flags;

  external FTSpanfunc graySpans;

  external FTSpanfunc blackSpans;

  external FTRasterBittestFunc bitTest;

  external FTRasterBitsetFunc bitSet;

  external ffi.Pointer<ffi.Void> user;

  external FTBbox clipBox;
}

typedef FTRasterParams = FTRasterParams_;

final class FTRasterrec_ extends ffi.Opaque {}

typedef FTRaster = ffi.Pointer<FTRasterrec_>;
typedef FTRasterNewfunc =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int Function(
          ffi.Pointer<ffi.Void> memory,
          ffi.Pointer<FTRaster> raster,
        )
      >
    >;
typedef FTRasterDonefunc =
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(FTRaster raster)>>;
typedef FTRasterResetfunc =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          FTRaster raster,
          ffi.Pointer<ffi.UnsignedChar> pool_base,
          ffi.UnsignedLong pool_size,
        )
      >
    >;
typedef FTRasterSetmodefunc =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int Function(
          FTRaster raster,
          ffi.UnsignedLong mode,
          ffi.Pointer<ffi.Void> args,
        )
      >
    >;
typedef FTRasterRenderfunc =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int Function(FTRaster raster, ffi.Pointer<FTRasterParams> params)
      >
    >;

final class FTRasterFuncs_ extends ffi.Struct {
  @ffi.UnsignedInt()
  external int glyphFormatAsInt;

  FTGlyphFormat_ get glyphFormat => FTGlyphFormat_.fromValue(glyphFormatAsInt);

  external FTRasterNewfunc rasterNew;

  external FTRasterResetfunc rasterReset;

  external FTRasterSetmodefunc rasterSetMode;

  external FTRasterRenderfunc rasterRender;

  external FTRasterDonefunc rasterDone;
}

typedef FTRasterFuncs = FTRasterFuncs_;
typedef FTBool = ffi.UnsignedChar;
typedef DartFTBool = int;
typedef FTFword = ffi.Short;
typedef DartFTFword = int;
typedef FTUfword = ffi.UnsignedShort;
typedef DartFTUfword = int;
typedef FTChar = ffi.SignedChar;
typedef DartFTChar = int;
typedef FTByte = ffi.UnsignedChar;
typedef DartFTByte = int;
typedef FTBytes = ffi.Pointer<FTByte>;
typedef FTTag = FTUint32;
typedef FTString = ffi.Char;
typedef DartFTString = int;
typedef FTShort = ffi.Short;
typedef DartFTShort = int;
typedef FTUshort = ffi.UnsignedShort;
typedef DartFTUshort = int;
typedef FTInt = ffi.Int;
typedef DartFTInt = int;
typedef FTUint = ffi.UnsignedInt;
typedef DartFTUint = int;
typedef FTLong = ffi.Long;
typedef DartFTLong = int;
typedef FTUlong = ffi.UnsignedLong;
typedef DartFTUlong = int;
typedef FTF2dot14 = ffi.Short;
typedef DartFTF2dot14 = int;
typedef FTF26dot6 = ffi.Long;
typedef DartFTF26dot6 = int;
typedef FTFixed = ffi.Long;
typedef DartFTFixed = int;
typedef FTError = ffi.Int;
typedef DartFTError = int;
typedef FTPointer = ffi.Pointer<ffi.Void>;
typedef FTOffset = ffi.Size;
typedef DartFTOffset = int;

final class FTUnitvector_ extends ffi.Struct {
  @FTF2dot14()
  external int x;

  @FTF2dot14()
  external int y;
}

typedef FTUnitvector = FTUnitvector_;

final class FTMatrix_ extends ffi.Struct {
  @FTFixed()
  external int xx;

  @FTFixed()
  external int xy;

  @FTFixed()
  external int yx;

  @FTFixed()
  external int yy;
}

typedef FTMatrix = FTMatrix_;

final class FTData_ extends ffi.Struct {
  external ffi.Pointer<FTByte> pointer;

  @FTUint()
  external int length;
}

typedef FTData = FTData_;
typedef FTGenericFinalizer =
    ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> object)>
    >;

final class FTGeneric_ extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  external FTGenericFinalizer finalizer;
}

typedef FTGeneric = FTGeneric_;
typedef FTListnode = ffi.Pointer<FTListnoderec_>;

final class FTListnoderec_ extends ffi.Struct {
  external FTListnode prev;

  external FTListnode next;

  external ffi.Pointer<ffi.Void> data;
}

final class FTListrec_ extends ffi.Struct {
  external FTListnode head;

  external FTListnode tail;
}

typedef FTList = ffi.Pointer<FTListrec_>;
typedef FTListnoderec = FTListnoderec_;
typedef FTListrec = FTListrec_;

final class FTGlyphMetrics_ extends ffi.Struct {
  @FTPos()
  external int width;

  @FTPos()
  external int height;

  @FTPos()
  external int horibearingx;

  @FTPos()
  external int horibearingy;

  @FTPos()
  external int horiadvance;

  @FTPos()
  external int vertbearingx;

  @FTPos()
  external int vertbearingy;

  @FTPos()
  external int vertadvance;
}

typedef FTGlyphMetrics = FTGlyphMetrics_;

final class FTBitmapSize_ extends ffi.Struct {
  @FTShort()
  external int height;

  @FTShort()
  external int width;

  @FTPos()
  external int size;

  @FTPos()
  external int xPpem;

  @FTPos()
  external int yPpem;
}

typedef FTBitmapSize = FTBitmapSize_;

final class FTLibraryrec_ extends ffi.Opaque {}

typedef FTLibrary = ffi.Pointer<FTLibraryrec_>;

final class FTModulerec_ extends ffi.Opaque {}

typedef FTModule = ffi.Pointer<FTModulerec_>;

final class FTDriverrec_ extends ffi.Opaque {}

typedef FTDriver = ffi.Pointer<FTDriverrec_>;

final class FTRendererrec_ extends ffi.Opaque {}

typedef FTRenderer = ffi.Pointer<FTRendererrec_>;
typedef FTFace = ffi.Pointer<FTFacerec_>;

enum FTEncoding_ {
  encodingNone(0),
  encodingMsSymbol(1937337698),
  encodingUnicode(1970170211),
  encodingSjis(1936353651),
  encodingPrc(1734484000),
  encodingBig5(1651074869),
  encodingWansung(2002873971),
  encodingJohab(1785686113),
  encodingAdobeStandard(1094995778),
  encodingAdobeExpert(1094992453),
  encodingAdobeCustom(1094992451),
  encodingAdobeLatin1(1818326065),
  encodingOldLatin2(1818326066),
  encodingAppleRoman(1634889070);

  static const encodingGb2312 = encodingPrc;
  static const encodingMsSjis = encodingSjis;
  static const encodingMsGb2312 = encodingPrc;
  static const encodingMsBig5 = encodingBig5;
  static const encodingMsWansung = encodingWansung;
  static const encodingMsJohab = encodingJohab;

  final int value;
  const FTEncoding_(this.value);

  static FTEncoding_ fromValue(int value) => switch (value) {
    0 => encodingNone,
    1937337698 => encodingMsSymbol,
    1970170211 => encodingUnicode,
    1936353651 => encodingSjis,
    1734484000 => encodingPrc,
    1651074869 => encodingBig5,
    2002873971 => encodingWansung,
    1785686113 => encodingJohab,
    1094995778 => encodingAdobeStandard,
    1094992453 => encodingAdobeExpert,
    1094992451 => encodingAdobeCustom,
    1818326065 => encodingAdobeLatin1,
    1818326066 => encodingOldLatin2,
    1634889070 => encodingAppleRoman,
    _ => throw ArgumentError('Unknown value for FTEncoding_: $value'),
  };

  @override
  String toString() {
    if (this == encodingSjis)
      return "FTEncoding_.encodingSjis, FTEncoding_.encodingMsSjis";
    if (this == encodingPrc)
      return "FTEncoding_.encodingPrc, FTEncoding_.encodingGb2312, FTEncoding_.encodingMsGb2312";
    if (this == encodingBig5)
      return "FTEncoding_.encodingBig5, FTEncoding_.encodingMsBig5";
    if (this == encodingWansung)
      return "FTEncoding_.encodingWansung, FTEncoding_.encodingMsWansung";
    if (this == encodingJohab)
      return "FTEncoding_.encodingJohab, FTEncoding_.encodingMsJohab";
    return super.toString();
  }
}

final class FTCharmaprec_ extends ffi.Struct {
  external FTFace face;

  @ffi.UnsignedInt()
  external int encodingAsInt;

  FTEncoding_ get encoding => FTEncoding_.fromValue(encodingAsInt);

  @FTUshort()
  external int platformId;

  @FTUshort()
  external int encodingId;
}

typedef FTCharmap = ffi.Pointer<FTCharmaprec_>;
typedef FTGlyphslot$1 = ffi.Pointer<FTGlyphslotrec_>;

final class FTSubglyphrec_ extends ffi.Opaque {}

typedef FTSubglyph = ffi.Pointer<FTSubglyphrec_>;

final class FTSlotInternalrec_ extends ffi.Opaque {}

typedef FTSlotInternal = ffi.Pointer<FTSlotInternalrec_>;

final class FTGlyphslotrec_ extends ffi.Struct {
  external FTLibrary library;

  external FTFace face;

  external FTGlyphslot$1 next;

  @FTUint()
  external int glyphIndex;

  external FTGeneric generic;

  external FTGlyphMetrics metrics;

  @FTFixed()
  external int linearhoriadvance;

  @FTFixed()
  external int linearvertadvance;

  external FTVector advance;

  @ffi.UnsignedInt()
  external int formatAsInt;

  FTGlyphFormat_ get format => FTGlyphFormat_.fromValue(formatAsInt);

  external FTBitmap bitmap;

  @FTInt()
  external int bitmapLeft;

  @FTInt()
  external int bitmapTop;

  external FTOutline outline;

  @FTUint()
  external int numSubglyphs;

  external FTSubglyph subglyphs;

  external ffi.Pointer<ffi.Void> controlData;

  @ffi.Long()
  external int controlLen;

  @FTPos()
  external int lsbDelta;

  @FTPos()
  external int rsbDelta;

  external ffi.Pointer<ffi.Void> other;

  external FTSlotInternal internal;
}

typedef FTGlyphslot = ffi.Pointer<FTGlyphslotrec_>;

final class FTSizeMetrics_ extends ffi.Struct {
  @FTUshort()
  external int xPpem;

  @FTUshort()
  external int yPpem;

  @FTFixed()
  external int xScale;

  @FTFixed()
  external int yScale;

  @FTPos()
  external int ascender;

  @FTPos()
  external int descender;

  @FTPos()
  external int height;

  @FTPos()
  external int maxAdvance;
}

typedef FTSizeMetrics = FTSizeMetrics_;

final class FTSizeInternalrec_ extends ffi.Opaque {}

typedef FTSizeInternal = ffi.Pointer<FTSizeInternalrec_>;

final class FTSizerec_ extends ffi.Struct {
  external FTFace face;

  external FTGeneric generic;

  external FTSizeMetrics metrics;

  external FTSizeInternal internal;
}

typedef FTSize = ffi.Pointer<FTSizerec_>;

final class FTFaceInternalrec_ extends ffi.Opaque {}

typedef FTFaceInternal = ffi.Pointer<FTFaceInternalrec_>;

final class FTFacerec_ extends ffi.Struct {
  @FTLong()
  external int numFaces;

  @FTLong()
  external int faceIndex;

  @FTLong()
  external int faceFlags;

  @FTLong()
  external int styleFlags;

  @FTLong()
  external int numGlyphs;

  external ffi.Pointer<FTString> familyName;

  external ffi.Pointer<FTString> styleName;

  @FTInt()
  external int numFixedSizes;

  external ffi.Pointer<FTBitmapSize> availableSizes;

  @FTInt()
  external int numCharmaps;

  external ffi.Pointer<FTCharmap> charmaps;

  external FTGeneric generic;

  external FTBbox bbox;

  @FTUshort()
  external int unitsPerEm;

  @FTShort()
  external int ascender;

  @FTShort()
  external int descender;

  @FTShort()
  external int height;

  @FTShort()
  external int maxAdvanceWidth;

  @FTShort()
  external int maxAdvanceHeight;

  @FTShort()
  external int underlinePosition;

  @FTShort()
  external int underlineThickness;

  external FTGlyphslot glyph;

  external FTSize size;

  external FTCharmap charmap;

  external FTDriver driver;

  external FTMemory memory;

  external FTStream stream;

  external FTListrec sizesList;

  external FTGeneric autohint;

  external ffi.Pointer<ffi.Void> extensions;

  external FTFaceInternal internal;
}

typedef FTCharmaprec = FTCharmaprec_;
typedef FTFacerec = FTFacerec_;
typedef FTSizerec = FTSizerec_;
typedef FTGlyphslotrec = FTGlyphslotrec_;

final class FTParameter_ extends ffi.Struct {
  @FTUlong()
  external int tag;

  external FTPointer data;
}

typedef FTParameter = FTParameter_;

final class FTOpenArgs_ extends ffi.Struct {
  @FTUint()
  external int flags;

  external ffi.Pointer<FTByte> memoryBase;

  @FTLong()
  external int memorySize;

  external ffi.Pointer<FTString> pathname;

  external FTStream stream;

  external FTModule driver;

  @FTInt()
  external int numParams;

  external ffi.Pointer<FTParameter> params;
}

typedef FTOpenArgs = FTOpenArgs_;

enum FTSizeRequestType_ {
  sizeRequestTypeNominal(0),
  sizeRequestTypeRealDim(1),
  sizeRequestTypeBbox(2),
  sizeRequestTypeCell(3),
  sizeRequestTypeScales(4),
  sizeRequestTypeMax(5);

  final int value;
  const FTSizeRequestType_(this.value);

  static FTSizeRequestType_ fromValue(int value) => switch (value) {
    0 => sizeRequestTypeNominal,
    1 => sizeRequestTypeRealDim,
    2 => sizeRequestTypeBbox,
    3 => sizeRequestTypeCell,
    4 => sizeRequestTypeScales,
    5 => sizeRequestTypeMax,
    _ => throw ArgumentError('Unknown value for FTSizeRequestType_: $value'),
  };
}

final class FTSizeRequestrec_ extends ffi.Struct {
  @ffi.UnsignedInt()
  external int typeAsInt;

  FTSizeRequestType_ get type => FTSizeRequestType_.fromValue(typeAsInt);

  @FTLong()
  external int width;

  @FTLong()
  external int height;

  @FTUint()
  external int horiresolution;

  @FTUint()
  external int vertresolution;
}

typedef FTSizeRequestrec = FTSizeRequestrec_;
typedef FTSizeRequest = ffi.Pointer<FTSizeRequestrec_>;

enum FTRenderMode_ {
  renderModeNormal(0),
  renderModeLight(1),
  renderModeMono(2),
  renderModeLcd(3),
  renderModeLcdV(4),
  renderModeSdf(5),
  renderModeMax(6);

  final int value;
  const FTRenderMode_(this.value);

  static FTRenderMode_ fromValue(int value) => switch (value) {
    0 => renderModeNormal,
    1 => renderModeLight,
    2 => renderModeMono,
    3 => renderModeLcd,
    4 => renderModeLcdV,
    5 => renderModeSdf,
    6 => renderModeMax,
    _ => throw ArgumentError('Unknown value for FTRenderMode_: $value'),
  };
}

enum FTKerningMode_ {
  kerningDefault(0),
  kerningUnfitted(1),
  kerningUnscaled(2);

  final int value;
  const FTKerningMode_(this.value);

  static FTKerningMode_ fromValue(int value) => switch (value) {
    0 => kerningDefault,
    1 => kerningUnfitted,
    2 => kerningUnscaled,
    _ => throw ArgumentError('Unknown value for FTKerningMode_: $value'),
  };
}

const int ftRenderPoolSize = 16384;

const int ftMaxModules = 32;

const int ftLlongMin = -9223372036854775808;

const int ftLlongMax = 9223372036854775807;

const int ftUllongMax = -1;

const int ftIntMax = 2147483647;

const int ftLongMax = 9223372036854775807;

const int ftIntMin = -2147483648;

const int ftLongMin = -9223372036854775808;

const int ftUintMax = 4294967295;

const int ftUlongMax = -1;

const int ftCharBit = 8;

const int ftUshortMax = 65535;

const int ftSizeofInt = 4;

const int ftSizeofLong = 8;

const int ftSizeofLongLong = 8;

const int ftOutlineContoursMax = 65535;

const int ftOutlinePointsMax = 65535;

const int ftOutlineNone = 0;

const int ftOutlineOwner = 1;

const int ftOutlineEvenOddFill = 2;

const int ftOutlineReverseFill = 4;

const int ftOutlineIgnoreDropouts = 8;

const int ftOutlineSmartDropouts = 16;

const int ftOutlineIncludeStubs = 32;

const int ftOutlineOverlap = 64;

const int ftOutlineHighPrecision = 256;

const int ftOutlineSinglePass = 512;

const int ftCurveTagOn = 1;

const int ftCurveTagConic = 0;

const int ftCurveTagCubic = 2;

const int ftCurveTagHasScanmode = 4;

const int ftCurveTagTouchX = 8;

const int ftCurveTagTouchY = 16;

const int ftCurveTagTouchBoth = 24;

const int ftRasterFlagDefault = 0;

const int ftRasterFlagAa = 1;

const int ftRasterFlagDirect = 2;

const int ftRasterFlagClip = 4;

const int ftRasterFlagSdf = 8;

const int ftFaceFlagScalable = 1;

const int ftFaceFlagFixedSizes = 2;

const int ftFaceFlagFixedWidth = 4;

const int ftFaceFlagSfnt = 8;

const int ftFaceFlagHorizontal = 16;

const int ftFaceFlagVertical = 32;

const int ftFaceFlagKerning = 64;

const int ftFaceFlagFastGlyphs = 128;

const int ftFaceFlagMultipleMasters = 256;

const int ftFaceFlagGlyphNames = 512;

const int ftFaceFlagExternalStream = 1024;

const int ftFaceFlagHinter = 2048;

const int ftFaceFlagCidKeyed = 4096;

const int ftFaceFlagTricky = 8192;

const int ftFaceFlagColor = 16384;

const int ftFaceFlagVariation = 32768;

const int ftFaceFlagSvg = 65536;

const int ftFaceFlagSbix = 131072;

const int ftFaceFlagSbixOverlay = 262144;

const int ftStyleFlagItalic = 1;

const int ftStyleFlagBold = 2;

const int ftOpenMemory = 1;

const int ftOpenStream = 2;

const int ftOpenPathname = 4;

const int ftOpenDriver = 8;

const int ftOpenParams = 16;

const int ftLoadDefault = 0;

const int ftLoadNoScale = 1;

const int ftLoadNoHinting = 2;

const int ftLoadRender = 4;

const int ftLoadNoBitmap = 8;

const int ftLoadVerticalLayout = 16;

const int ftLoadForceAutohint = 32;

const int ftLoadCropBitmap = 64;

const int ftLoadPedantic = 128;

const int ftLoadIgnoreGlobalAdvanceWidth = 512;

const int ftLoadNoRecurse = 1024;

const int ftLoadIgnoreTransform = 2048;

const int ftLoadMonochrome = 4096;

const int ftLoadLinearDesign = 8192;

const int ftLoadSbitsOnly = 16384;

const int ftLoadNoAutohint = 32768;

const int ftLoadColor = 1048576;

const int ftLoadComputeMetrics = 2097152;

const int ftLoadBitmapMetricsOnly = 4194304;

const int ftLoadNoSvg = 16777216;

const int ftLoadAdvanceOnly = 256;

const int ftLoadSvgOnly = 8388608;

const int ftLoadTargetNormal = 0;

const int ftLoadTargetLight = 65536;

const int ftLoadTargetMono = 131072;

const int ftLoadTargetLcd = 196608;

const int ftLoadTargetLcdV = 262144;

const int ftSubglyphFlagArgsAreWords = 1;

const int ftSubglyphFlagArgsAreXyValues = 2;

const int ftSubglyphFlagRoundXyToGrid = 4;

const int ftSubglyphFlagScale = 8;

const int ftSubglyphFlagXyScale = 64;

const int ftSubglyphFlag2x2 = 128;

const int ftSubglyphFlagUseMyMetrics = 512;

const int ftFstypeInstallableEmbedding = 0;

const int ftFstypeRestrictedLicenseEmbedding = 2;

const int ftFstypePreviewAndPrintEmbedding = 4;

const int ftFstypeEditableEmbedding = 8;

const int ftFstypeNoSubsetting = 256;

const int ftFstypeBitmapEmbeddingOnly = 512;
